### ISSUE TITLE
这是我见过的最暴力的求ARIMA p, q值的函数

### ISSUE THREAD

**Issue by shwangdev** [wnma3mz/python_ds_dm_note#1]
https://github.com/apachecn/python_data_analysis_and_mining_action/blob/b138d75c0211d3a89b2e08f706f918034730ea9e/chapter11/code.py#L95

**Comment by wnma3mz** [comment]
hhhh，书上是这么实现的，肯定有更优雅的解决代码and第三方包

**Comment by wizardforcel** [comment]
这就是网格搜索啊。p和q本质上是超参数。

**Comment by shwangdev** [comment]
@wizardforcel  P, Q是由自相关和偏相关系数直接决定的。不需这样搜索。写书的人也是一知半解。这种书不看也罢。

**Comment by wizardforcel** [comment]
@wxjeacen P 和 Q 并没有解析解，它们是使自相关和偏相关系数最优的值，等于说还是搜索问题。

网格搜索从结果上来看等价于自相关和偏相关系数的最优化。与之相比，心智负担更小，但开销可能更大。

**Comment by shwangdev** [comment]
@wizardforcel 你真的懂自相关和偏相关系数吗？我还第一次听说这两个系数有最优值。
