### ISSUE TITLE
 y = np.sort(y)

### ISSUE THREAD

**Issue by wyscjm** [wnma3mz/python_ds_dm_note#2]
https://github.com/apachecn/python_data_analysis_and_mining_action/blob/b138d75c0211d3a89b2e08f706f918034730ea9e/chapter3/code.py#L41

should use below code under anaconda
```
    y = p['fliers'][0].get_ydata()
    y = np.sort(y)
```

**Comment by wnma3mz** [comment]
Thx, i have changed that.
