### ISSUE TITLE
7law.zip 解压的时候提示压缩包损坏

### ISSUE THREAD

**Issue by runpsw** [wnma3mz/python_ds_dm_note#3]
解压的时候提示压缩包以损坏或压缩格式不对

**Comment by wnma3mz** [comment]
很抱歉这么晚回复。不知道是怎么下载的？是如何解压的？

我刚刚放了一份到百度网盘和OneDrive，以供下载。

链接: https://pan.baidu.com/s/1f8E3jj7fO2JrzlW7Kw8j-A 提取码: mcpb 

https://1drv.ms/u/s!ApdQKM4OiicmlVaPVOJ7zk2Iihin?e=KpZ5IQ
