### ISSUE TITLE
【异常反馈】无法获取Git LFS中的内容

### ISSUE THREAD

**Issue by Dragon1573** [wnma3mz/python_ds_dm_note#4]
开发者团队 @apachecn 及其下属成员：

你们好！我在使用 **Git Bash** 和 **SourceTree** 两款应用程序尝试将本仓库克隆至本地时，执行以下操作会发生错误：

```text
legen@Legend1949 MINGW64 /Repos/python_data_analysis_and_mining_action (master)
$ git pull
Already up to date.

legen@Legend1949 MINGW64 /Repos/python_data_analysis_and_mining_action (master)
$ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/apachecn/python_data_analysis_and_mining_action.git/info/lfs'
```

根据 https://www.codetd.com/article/7650047 的指示查询我 GitHub 账户的 [Billing](https://github.com/settings/billing) 菜单，获得以下内容。截图内容显示我的 **Git LFS** 存储空间及带宽都没有超出限制：

![image](https://user-images.githubusercontent.com/49941141/70134478-239ac200-16c3-11ea-9ea9-82d426411ec9.png)

请问我遇到的错误需要如何解决？只能付费购买更高的存储空间和带宽吗？谢谢！

**Comment by wnma3mz** [comment]
@Dragon1573 很抱歉这么晚回复，这个问题应该是我们这边的问题。您可以参考这个issue的回复来下载所需数据。
https://github.com/apachecn/python_data_analysis_and_mining_action/issues/3

**Comment by Dragon1573** [comment]
此 Issues 是我在12天前提出的，我已在约10天前完成所需任务，暂时不需要再下载此数据了。

感谢 @wnma3mz 能给予我回复并为我提供解决方案，谢谢！
